name: linux-install
on: [push, pull_request]
jobs:
  build-dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup perl locallib
        run: .github/scripts/setup_perl_locallib.sh
      - name: install cpanm
        run: cpan App::cpanminus
      - name: install dependencies
        run: cpanm -v --installdeps .
